---

# https://github.com/babel/babel-eslint
parser: babel-eslint

env:
  node: true

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

extends:
  - 'airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

rules:
  no-console: off

reportUnusedDisableDirectives: true
